version: '2.1'

services:
   varnish:
     environment:
       - VARNISH_BACKEND_IP=127.0.0.1
       - VARNISH_BACKEND_PORT=8080
       - VARNISH_LISTEN_ADDRESS=0.0.0.0
       - VARNISH_LISTEN_PORT=80
       - VARNISH_MEMORY_SIZE=100M
       - VARNISH_ADMIN_PORT
     build:
       context: .
       args:
         - VERSION=4.1.8
         - EXPOSE_PORT=80
     image: bugsonfire/varnish:4.1.8
     container_name: varnish
     volumes:
       - /etc/varnish:/etc/varnish
     ports:
       - "80:80"
       - "6082:6082"
     shm_size: 100M
     stdin_open: true
     tty: true
